[log]
#level = "DEBUG"

[api]
dashboard = true
insecure = true

[providers]
    [providers.docker]
        exposedByDefault = false
        endpoint = "unix:///var/run/docker.sock"
        network = "listmonk_ingress"

[entryPoints]
    [entryPoints.web]
        address = ":80"
    [entryPoints.web.http]
        [entryPoints.web.http.redirections]
            [entryPoints.web.http.redirections.entrypoint]
            to = "websecure"
            scheme = "https"

    [entryPoints.websecure]
        address = ":443"

[certificatesResolvers.letsencrypt.acme]
    email = "hallo+letsencrypt@kalk.space"
    storage = "/var/traefik_certs/acme.json"
    [certificatesResolvers.letsencrypt.acme.httpChallenge]
        entryPoint = "web"

[serversTransport]
    insecureSkipVerify = true
