---
- name: set authorized keys for kalkspace admin team
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "https://github.com/{{ item }}.keys"
    comment: "{{ item }}@github"

  loop:
    - buecherwurmmm
    - haralk
    - m0ppers
    - mraerino
    - sangyye
